<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.BoolResponse</code>
 */
class BoolResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool bool = 1;</code>
     */
    private $bool = false;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bool bool = 1;</code>
     * @return bool
     */
    public function getBool()
    {
        return $this->bool;
    }

    /**
     * Generated from protobuf field <code>bool bool = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setBool($var)
    {
        GPBUtil::checkBool($var);
        $this->bool = $var;

        return $this;
    }

}

