<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Confirmations</code>
 */
class Confirmations extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 confirmations = 1;</code>
     */
    private $confirmations = 0;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>uint32 confirmations = 1;</code>
     * @return int
     */
    public function getConfirmations()
    {
        return $this->confirmations;
    }

    /**
     * Generated from protobuf field <code>uint32 confirmations = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setConfirmations($var)
    {
        GPBUtil::checkUint32($var);
        $this->confirmations = $var;

        return $this;
    }

}

