<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.FeeLevelSelection</code>
 */
class FeeLevelSelection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.FeeLevel feeLevel = 1;</code>
     */
    private $feeLevel = 0;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.pb.FeeLevel feeLevel = 1;</code>
     * @return int
     */
    public function getFeeLevel()
    {
        return $this->feeLevel;
    }

    /**
     * Generated from protobuf field <code>.pb.FeeLevel feeLevel = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setFeeLevel($var)
    {
        GPBUtil::checkEnum($var, \Pb\FeeLevel::class);
        $this->feeLevel = $var;

        return $this;
    }

}

