<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

/**
 * Protobuf enum <code>Pb\FeeLevel</code>
 */
class FeeLevel
{
    /**
     * Generated from protobuf enum <code>ECONOMIC = 0;</code>
     */
    const ECONOMIC = 0;
    /**
     * Generated from protobuf enum <code>NORMAL = 1;</code>
     */
    const NORMAL = 1;
    /**
     * Generated from protobuf enum <code>PRIORITY = 2;</code>
     */
    const PRIORITY = 2;
}

