<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

/**
 * Protobuf enum <code>Pb\KeyPurpose</code>
 */
class KeyPurpose
{
    /**
     * Generated from protobuf enum <code>INTERNAL = 0;</code>
     */
    const INTERNAL = 0;
    /**
     * Generated from protobuf enum <code>EXTERNAL = 1;</code>
     */
    const EXTERNAL = 1;
}

