<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.KeySelection</code>
 */
class KeySelection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.KeyPurpose purpose = 1;</code>
     */
    private $purpose = 0;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.pb.KeyPurpose purpose = 1;</code>
     * @return int
     */
    public function getPurpose()
    {
        return $this->purpose;
    }

    /**
     * Generated from protobuf field <code>.pb.KeyPurpose purpose = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPurpose($var)
    {
        GPBUtil::checkEnum($var, \Pb\KeyPurpose::class);
        $this->purpose = $var;

        return $this;
    }

}

