<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Output</code>
 */
class Output extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes scriptPubKey = 1;</code>
     */
    private $scriptPubKey = '';
    /**
     * Generated from protobuf field <code>uint64 value = 2;</code>
     */
    private $value = 0;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>bytes scriptPubKey = 1;</code>
     * @return string
     */
    public function getScriptPubKey()
    {
        return $this->scriptPubKey;
    }

    /**
     * Generated from protobuf field <code>bytes scriptPubKey = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setScriptPubKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->scriptPubKey = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 value = 2;</code>
     * @return int|string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>uint64 value = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkUint64($var);
        $this->value = $var;

        return $this;
    }

}

