<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Peer</code>
 */
class Peer extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    private $address = '';
    /**
     * Generated from protobuf field <code>uint64 bytesSent = 2;</code>
     */
    private $bytesSent = 0;
    /**
     * Generated from protobuf field <code>uint64 bytesReceived = 3;</code>
     */
    private $bytesReceived = 0;
    /**
     * Generated from protobuf field <code>bool connected = 4;</code>
     */
    private $connected = false;
    /**
     * Generated from protobuf field <code>int32 ID = 5;</code>
     */
    private $ID = 0;
    /**
     * Generated from protobuf field <code>int32 lastBlock = 6;</code>
     */
    private $lastBlock = 0;
    /**
     * Generated from protobuf field <code>uint32 protocolVersion = 7;</code>
     */
    private $protocolVersion = 0;
    /**
     * Generated from protobuf field <code>string services = 8;</code>
     */
    private $services = '';
    /**
     * Generated from protobuf field <code>string userAgent = 9;</code>
     */
    private $userAgent = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timeConnected = 10;</code>
     */
    private $timeConnected = null;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 bytesSent = 2;</code>
     * @return int|string
     */
    public function getBytesSent()
    {
        return $this->bytesSent;
    }

    /**
     * Generated from protobuf field <code>uint64 bytesSent = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBytesSent($var)
    {
        GPBUtil::checkUint64($var);
        $this->bytesSent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 bytesReceived = 3;</code>
     * @return int|string
     */
    public function getBytesReceived()
    {
        return $this->bytesReceived;
    }

    /**
     * Generated from protobuf field <code>uint64 bytesReceived = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBytesReceived($var)
    {
        GPBUtil::checkUint64($var);
        $this->bytesReceived = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool connected = 4;</code>
     * @return bool
     */
    public function getConnected()
    {
        return $this->connected;
    }

    /**
     * Generated from protobuf field <code>bool connected = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setConnected($var)
    {
        GPBUtil::checkBool($var);
        $this->connected = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ID = 5;</code>
     * @return int
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>int32 ID = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkInt32($var);
        $this->ID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 lastBlock = 6;</code>
     * @return int
     */
    public function getLastBlock()
    {
        return $this->lastBlock;
    }

    /**
     * Generated from protobuf field <code>int32 lastBlock = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setLastBlock($var)
    {
        GPBUtil::checkInt32($var);
        $this->lastBlock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 protocolVersion = 7;</code>
     * @return int
     */
    public function getProtocolVersion()
    {
        return $this->protocolVersion;
    }

    /**
     * Generated from protobuf field <code>uint32 protocolVersion = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setProtocolVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->protocolVersion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string services = 8;</code>
     * @return string
     */
    public function getServices()
    {
        return $this->services;
    }

    /**
     * Generated from protobuf field <code>string services = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setServices($var)
    {
        GPBUtil::checkString($var, True);
        $this->services = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userAgent = 9;</code>
     * @return string
     */
    public function getUserAgent()
    {
        return $this->userAgent;
    }

    /**
     * Generated from protobuf field <code>string userAgent = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setUserAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->userAgent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timeConnected = 10;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getTimeConnected()
    {
        return $this->timeConnected;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timeConnected = 10;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimeConnected($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timeConnected = $var;

        return $this;
    }

}

