<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.SignatureList</code>
 */
class SignatureList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pb.Signature sigs = 1;</code>
     */
    private $sigs;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Signature sigs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSigs()
    {
        return $this->sigs;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Signature sigs = 1;</code>
     * @param \Pb\Signature[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSigs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Signature::class);
        $this->sigs = $arr;

        return $this;
    }

}

