<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.SweepInfo</code>
 */
class SweepInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .pb.Utxo utxos = 1;</code>
     */
    private $utxos;
    /**
     * Generated from protobuf field <code>string address = 2;</code>
     */
    private $address = '';
    /**
     * Generated from protobuf field <code>string key = 3;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>bytes redeemScript = 4;</code>
     */
    private $redeemScript = '';
    /**
     * Generated from protobuf field <code>.pb.FeeLevel feeLevel = 5;</code>
     */
    private $feeLevel = 0;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Utxo utxos = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUtxos()
    {
        return $this->utxos;
    }

    /**
     * Generated from protobuf field <code>repeated .pb.Utxo utxos = 1;</code>
     * @param \Pb\Utxo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUtxos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Pb\Utxo::class);
        $this->utxos = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 2;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes redeemScript = 4;</code>
     * @return string
     */
    public function getRedeemScript()
    {
        return $this->redeemScript;
    }

    /**
     * Generated from protobuf field <code>bytes redeemScript = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRedeemScript($var)
    {
        GPBUtil::checkString($var, False);
        $this->redeemScript = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.pb.FeeLevel feeLevel = 5;</code>
     * @return int
     */
    public function getFeeLevel()
    {
        return $this->feeLevel;
    }

    /**
     * Generated from protobuf field <code>.pb.FeeLevel feeLevel = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setFeeLevel($var)
    {
        GPBUtil::checkEnum($var, \Pb\FeeLevel::class);
        $this->feeLevel = $var;

        return $this;
    }

}

