<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.Tx</code>
 */
class Tx extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string txid = 1;</code>
     */
    private $txid = '';
    /**
     * Generated from protobuf field <code>int64 value = 2;</code>
     */
    private $value = 0;
    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     */
    private $height = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 4;</code>
     */
    private $timestamp = null;
    /**
     * Generated from protobuf field <code>bool watchOnly = 5;</code>
     */
    private $watchOnly = false;
    /**
     * Generated from protobuf field <code>bytes raw = 6;</code>
     */
    private $raw = '';

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string txid = 1;</code>
     * @return string
     */
    public function getTxid()
    {
        return $this->txid;
    }

    /**
     * Generated from protobuf field <code>string txid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTxid($var)
    {
        GPBUtil::checkString($var, True);
        $this->txid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 value = 2;</code>
     * @return int|string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>int64 value = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     * @return int
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * Generated from protobuf field <code>int32 height = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setHeight($var)
    {
        GPBUtil::checkInt32($var);
        $this->height = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool watchOnly = 5;</code>
     * @return bool
     */
    public function getWatchOnly()
    {
        return $this->watchOnly;
    }

    /**
     * Generated from protobuf field <code>bool watchOnly = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setWatchOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->watchOnly = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes raw = 6;</code>
     * @return string
     */
    public function getRaw()
    {
        return $this->raw;
    }

    /**
     * Generated from protobuf field <code>bytes raw = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setRaw($var)
    {
        GPBUtil::checkString($var, False);
        $this->raw = $var;

        return $this;
    }

}

